### PR TITLE
Feat/update cmcc and end coin

### PR DESCRIPTION
**Pull request by erwin-huang**

### CODE REVIEW

**Comment by LukeSamkharadze** [comment]
Oh you branched out from `main`, okay..

**Comment by erwin-huang** [comment]
It's deleted on `develop` branch, I just updated the `main` branch, because I think the `develop` branch is not ready to be deployed right? Note: we have `KAPEX` data on `summitswap-data` 

image

**Comment by erwin-huang** [comment]
@LukeSamkharadze I branched out from `main`, I'm afraid I will mess up if I deploy the `develop` branch,
Should I just remove the `KAPEX` from `summitswap-data`?
so we can use the `develop` branch for the next deployment?
Note: because KAPEX is not ready to launch yet I guess

**Comment by LukeSamkharadze** [comment]
Yep we should remove kapex in data

**Comment by erwin-huang** [comment]
Okay, Luka, my bad

**Pull request merged**
