### PR TITLE
Feat/whitelabel nft

### PR DESCRIPTION
**Pull request by sxio**

### CODE REVIEW

**Review by LukeSamkharadze — COMMENTED** [review]
@sxio can you merge this into latest develop and fix the failing tests?

**Review by LukeSamkharadze — COMMENTED** [review]
Every page if possible should work without even having metamask installed, like it did before

**Review by LukeSamkharadze — COMMENTED** [review]
Reveal collection still doesn't do anything.

I think if collection is already revealed we should hide that button otherwise if it's not reveled it should reveal and then hide. Also for revealing confirmation would be good

**Review by LukeSamkharadze — COMMENTED** [review]
When switching pages and I think we can directly ask them to switch network instead of them clicking `unlock wallet` every time

**Comment by sxio** [comment]
> Reveal collection still doesn't do anything.
> 
> I think if collection is already revealed we should hide that button otherwise if it's not reveled it should reveal and then hide. Also for revealing confirmation would be good

i found out that on the PR AWS link the reveal collection doesnt do anything because of the difference in mongodb which, PR AWS use dx's mongodb, when i ran locally the reveal collection ran fine.

**Pull request merged**
